services:
  - type: web
    name: calculator-client
    env: node
    buildCommand: npm install && npm run build
    startCommand: serve -s build
    envVars:
      - key: REACT_APP_API_URL
        value: https://calculator-api-on2h.onrender.com/api
    healthCheckPath: /
    autoDeploy: true
    plan: free
    disk:
      name: tmp
      mountPath: /tmp
      sizeGB: 1

  - type: web
    name: calculator-api
    env: node
    buildCommand: npm install && npm run build
    startCommand: node dist/index.js
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: PORT
        value: 10000
      - key: CLIENT_URL
        value: https://calculator-client-4vmq.onrender.com
    healthCheckPath: /api/auth/register
    autoDeploy: true
    plan: free
    disk:
      name: tmp
      mountPath: /tmp
      sizeGB: 1 